name: Setup GO

runs:
  using: composite
  steps:
    - name: Get GO Version
      id: go-version
      shell: bash
      run: |
        GO_VERSION=$(grep -E '^go[[:space:]]+[0-9]+' go.mod | awk '{print $2}')
        echo "GO=$GO_VERSION" >> $GITHUB_OUTPUT

    - name: Setup GO  
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
      with:
        go-version: ${{ steps.go-version.outputs.GO }}
