name: Setup GO

runs:
  using: composite
  steps:
    - name: Get GO Version
      id: go-version
      shell: bash
      run: |
        GO_VERSION=$(grep -E '^go[[:space:]]+[0-9]+' go.mod | awk '{print $2}')
        echo "GO=$GO_VERSION" >> $GITHUB_OUTPUT

    - name: Setup GO  
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
      with:
        go-version: ${{ steps.go-version.outputs.GO }}
