name: Setup GO

runs:
  using: composite
  steps:
    - name: Get GO Version
      id: go-version
      shell: bash
      run: |
        GO_VERSION=$(grep -E '^go[[:space:]]+[0-9]+' go.mod | awk '{print $2}')
        echo "GO=$GO_VERSION" >> $GITHUB_OUTPUT

    - name: Setup GO  
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
      with:
        go-version: ${{ steps.go-version.outputs.GO }}
