---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: ci
  image: rancher/dapper:v0.5.4
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
      - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
      - "dist/artifacts/*"
  when:
    ref:
      - refs/tags/*
    event:
      - tag

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: "rancher/rancher-csp-adapter"
    tag: "${DRONE_TAG}-amd64"
  when:
    event:
    - tag

- name: docker-build
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    repo: "rancher/rancher-csp-adapter"
    tag: "${DRONE_COMMIT}-amd64"
    dry_run: true
  when:
    event:
    - pull_request

- name: ecr-publish
  image: plugins/ecr
  settings:
    dockerfile: package/Dockerfile
    access_key:
      from_secret: ecr_access_key
    secret_key:
      from_secret: ecr_secret_key
    registry:
      from_secret: aws_registry_id
    repo: suse/rancher/rancher-csp-adapter
    tag: "${DRONE_TAG}"
  when:
    event:
    - tag

- name: ecr-publish-eu
  image: plugins/ecr
  settings:
    dockerfile: package/Dockerfile
    access_key:
      from_secret: ecr_access_key_eu
    secret_key:
      from_secret: ecr_secret_key_eu
    registry:
      from_secret: aws_registry_id_eu
    repo: suse/rancher/rancher-csp-adapter-eu
    tag: "${DRONE_TAG}"
  when:
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---

kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: ci
  image: rancher/dapper:v0.5.4
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
      - sha256
    checksum_file: CHECKSUMsum-arm64.txt
    checksum_flatten: true
    files:
      - "dist/artifacts/*"
  when:
    ref:
      - refs/tags/*
    event:
      - tag

- name: docker-build
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    repo: "rancher/rancher-csp-adapter"
    tag: "${DRONE_COMMIT}-arm64"
    dry_run: true
  when:
    event:
    - pull_request

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: "rancher/rancher-csp-adapter"
    tag: "${DRONE_TAG}-arm64"
  when:
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---

kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest:1.4.0
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    target: "rancher/rancher-csp-adapter:${DRONE_TAG}"
    template: "rancher/rancher-csp-adapter:${DRONE_TAG}-ARCH"
  when:
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

depends_on:
- linux-amd64
- linux-arm64
