#!/bin/bash

files=$(find ./dist/artifacts -type f -name "*.txt")

# Verify checksums from the files
if echo "$files" | xargs sha256sum --check ; then
    echo "Checksum passed"
    exit 0
else
    echo "Checksum failed"
    exit 1
fi
