name: Build
on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6 

      - name: Setup GO
        uses: ./.github/actions/setup

      - name: Run Build
        run: make build

      - name: Run Tests
        run: make test
