name: Build
on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6 

      - name: Setup GO
        uses: ./.github/actions/setup

      - name: Run Build
        run: make build

      - name: Run Tests
        run: make test
