name: Release
on:
  push:
    tags: 
      - 'v*'

# Needed to create the release
permissions:
  contents: write
  id-token: write

# Needed to create the release and use gh cli
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4 

      - name: Create a Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          prerelease: true

  build-and-push-amd64:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
      - name: Checkout Code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4 

      - name: Setup GO
        uses: ./.github/actions/setup

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
        with:
          buildkitd-flags: --debug

      - name: Setup QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Run CI
        run: make ci

      - name: Generate Checksum
        run: |
          cd dist/artifacts 
          sha256sum * > sha256sum-amd64.txt

      - name: Upload Assets
        run: |
          ASSETS_DIR="dist/artifacts"
          TAG=${{ github.ref_name }}
          for file in $ASSETS_DIR/*; do
            gh release upload $TAG $file --repo ${{ github.repository }}
          done

      - name: Build Manifest
        id: metadata
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5
        with:
          images: |
            docker.io/rancher/rancher-csp-adapter
            709825985650.dkr.ecr.us-east-1.amazonaws.com/suse/rancher/rancher-csp-adapter
          flavor: |
            latest=false

      - name: Read Secrets
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials registry | PRIME_REGISTRY ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials username | PRIME_REGISTRY_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials password | PRIME_REGISTRY_PASSWORD ;
            secret/data/github/repo/${{ github.repository }}/aws/aws-rancher-csp-adapter-ecr/credentials accessKeyId | ECR_ACCESS_KEY ;
            secret/data/github/repo/${{ github.repository }}/aws/aws-rancher-csp-adapter-ecr/credentials secretAccessKey | ECR_SECRET_KEY ;
            secret/data/github/repo/${{ github.repository }}/aws/aws-rancher-csp-adapter-ecr-eu/credentials accessKeyId | ECR_ACCESS_KEY_EU ;
            secret/data/github/repo/${{ github.repository }}/aws/aws-rancher-csp-adapter-ecr-eu/credentials secretAccessKey | ECR_SECRET_KEY_EU ;

      - name: Publish manifest
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        with:
          image: rancher-csp-adapter
          tag: ${{ github.ref_name }}
          platforms: linux/amd64
          public-registry: docker.io
          public-repo: rancher
          public-username: ${{ env.DOCKER_USERNAME }}
          public-password: ${{ env.DOCKER_PASSWORD }}
          prime-registry: ${{ env.PRIME_REGISTRY }}
          prime-repo: rancher
          prime-username: ${{ env.PRIME_REGISTRY_USERNAME }}
          prime-password: ${{ env.PRIME_REGISTRY_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5
        with:
          aws-access-key-id: ${{ env.ECR_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.ECR_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: 709825985650.dkr.ecr.us-east-1.amazonaws.com

      - name: Push Images to Registries
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          file: package/Dockerfile
          platforms: linux/amd64

      - name: Build Manifest for EU Registry Images
        id: metadata_eu
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5
        with:
          images: |
            709825985650.dkr.ecr.us-east-1.amazonaws.com/suse/rancher/rancher-csp-adapter-eu
          flavor: |
            latest=false

      - name: Configure AWS credentials for EU Registry
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5
        with:
          aws-access-key-id: ${{ env.ECR_ACCESS_KEY_EU }}
          aws-secret-access-key: ${{ env.ECR_SECRET_KEY_EU }}
          aws-region: us-east-1

      - name: Login to ECR for EU Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: 709825985650.dkr.ecr.us-east-1.amazonaws.com

      - name: Push Images to EU Registry
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: true
          tags: ${{ steps.metadata_eu.outputs.tags }}
          labels: ${{ steps.metadata_eu.outputs.labels }}
          file: package/Dockerfile
          platforms: linux/amd64
